CREATE TABLE security_logs_raw (
                                   log_id bigserial primary key not null,
                                   event_time timestamptz default now(),
                                   username VARCHAR(30) NOT NULL,
                                   user_role VARCHAR(20) NOT NULL DEFAULT ('guest'),
                                   account_status VARCHAR (20),
                                   ip_address inet NOT NULL,
                                   port_number int NOT NULL,
                                   device_type VARCHAR(20),
                                   operating_system VARCHAR(20),
                                   browser_name VARCHAR(20),
                                   location_city VARCHAR(30) NOT NULL,
                                   location_region VARCHAR(30),
                                   location_country CHAR(2) NOT NULL,
                                   event_type VARCHAR(20) NOT NULL,
                                   event_category VARCHAR(20),
                                   action_taken VARCHAR(20),
                                   status VARCHAR(20),
                                   severity VARCHAR(10),
                                   resource_type VARCHAR(30),
                                   resource_name VARCHAR(20),
                                   session_id BIGSERIAL,
                                   failure_reason VARCHAR(200),
                                   risk_score INT NOT NULL,
                                   watchlist_flag BOOLEAN DEFAULT FALSE,
                                   notes VARCHAR (200)
);